name: ToDo Build

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - 'task4'

env:
  gradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

jobs:
  build-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        shell: bash
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :app:telegramReportForDebug $gradleFlags
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/*.apk